LawwlUp/Models/AppUser.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using LawwlUp.Data.Enums;

namespace LawwlUp.Models
{
    public class AppUser
    {
        [Key]
        public string Id { get; set; }
        public UserCategory UserCategory { get; set; }
        public ICollection<Test> Tests{get; set;}
        public ICollection<PassedTest> PassedTests { get; set; }
    }
}

LawwlUp/Models/ErrorViewModel.cs
namespace LawwlUp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LawwlUp/Models/Guide.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LawwlUp.Models
{
    public class Guide
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string? Image { get; set; }
        public string? Information { get; set; }
    }
}

LawwlUp/Models/PassedTest.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LawwlUp.Models
{
    public class PassedTest
    {
        [Key]
        public int Id { get; set; }

        public int Score { get; set; }
        public int Point { get; set; }
        public string ?Image { get; set; }
        
        [ForeignKey("Test")]
        public int TestId { get; set; }

        [ForeignKey("AppUser")]
        public string? AppUserId { get; set; }
        public AppUser? AppUser { get; set; }
    }
}

LawwlUp/Models/Question.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LawwlUp.Models
{
    public class Question
    {
        [Key]
        public int Id { get; set; }
        public string Title{ get; set; }
        public string Answer { get; set; }
        
        [ForeignKey("Test")]
        public int TestId { get; set; }
        public Test ?Test { get; set; }
    }
}

LawwlUp/Models/Test.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LawwlUp.Models
{
    public class Test
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int CountQuestions { get; set; }
        public int Point { get; set; }
        public string? Image { get; set; }
    }
}

LawwlUp/Controllers/GuideController.cs
using Microsoft.AspNetCore.Mvc;
using LawwlUp.Data;

namespace LawwlUp.Controllers
{
    public class GuideController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GuideController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Guides.ToList());
        }

        public IActionResult Detail(int id)
        {
            return View(_context.Guides.FirstOrDefault(guid => guid.Id == id));
        }
    }
}

LawwlUp/Controllers/HomeController.cs
using LawwlUp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LawwlUp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LawwlUp/Controllers/PassedTestController.cs
using LawwlUp.Data;
using Microsoft.AspNetCore.Mvc;

namespace LawwlUp.Controllers
{
    public class PassedTestController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PassedTestController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var Tests = _context.PassedTests.ToList();
            return View(Tests);
        }
    }
}

LawwlUp/Controllers/TestController.cs
using LawwlUp.Data;
using Microsoft.AspNetCore.Mvc;

namespace LawwlUp.Controllers
{
    public class TestController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TestController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var Tests = _context.Tests.ToList();
            return View(Tests);
        }
    }
}

LawwlUp/Views/Guide/Detail.cshtml
@model Guide
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="jumbotron">
    <h1 class="mx-auto d-block text-center">@Model.Title</h1>
    <img src ="@Model.Image" width = "70%" class="mx-auto d-block"/>
    <h4>@Model.Description</h4>
    <p class="lead">@Model.Information</p>
    <a type="btn btn-succes" asp-controller="Guide" asp-action="Index"
       class="btn btn-sm btn-outline-secondary">Вернуться назад</a>
</div>

LawwlUp/Views/Guide/Index.cshtml
@model IEnumerable<Guide>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1 class="text-center"> Справочная информация</h1>


<div class="container">
    <div class ="row">
    @foreach(var item in Model)
    {
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <img src="@item.Image">
                <div class="card-header"> @item.Title.</div>
                <div class="card-body">
                    <p class="card-text">@item.Description</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <a type="btn btn-succes" asp-controller="Guide" asp-action="Detail" asp-route-id="@item.Id"
                        class="btn btn-sm btn-outline-secondary">Подробнее</a>
                    </div>
                </div>
            </div>
        </div>
    }
    </div>
</div>

LawwlUp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">PROFKOM</h1>
        <p class="lead text-muted"> Это про студенчество, Будь первым!</p>
        <p>
            <a href="#" class="btn btn-primary my-2">Вступай в профсоюз</a>
            <a href="#" class="btn btn-secondary my-2">Развивайся</a>
        </p>
    </div>
</section>

LawwlUp/Views/PassedTest/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1> Список пройденных тестов вами:</h1>

LawwlUp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LawwlUp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LawwlUp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LawwlUp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная страница</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Index">Тесты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PassedTest" asp-action="Index">Пройденные тесты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Guide" asp-action="Index">Справочник</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LawwlUp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LawwlUp/Views/Test/Index.cshtml
@model IEnumerable<Test>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>This is all tests of this users</h1>


<div class="container">
    <div class ="row">
    @foreach(var item in Model)
    {
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header"> @item.Title.</div>
                <div class="card-body">
                    <p class="card-text">@item.Description.</p>
                    <p class="card-text"> Количетсов вопросов : @item.CountQuestions.</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <button type="button" class="btn btn-sm btn-outline-secondary">Пройти Тест</button>
                    </div>
                </div>
            </div>
        </div>
    }

    </div>
</div>